const descriptivePrompts = [
  {
    "number": 1,
    "category": "Describing People",
    "title": "1. Teacher who had a great influence on you",
    "prompt": "Describe a teacher who had a great influence on you.",
    "model": "I would like to talk about my current junior high school English teacher, Ms. Lin. She has a major impact on me because her classes are always lively and interactive, rather than just memorizing grammar rules. Whenever I make mistakes, she patiently encourages me to try again without feeling embarrassed. Thanks to her guidance, I have gradually built up my confidence in speaking English. She doesn't just teach from the textbook; she also shares interesting Western cultural stories, which inspire me to dream about studying abroad in the future.",
    "keywords": [
      "Junior high school (國中)",
      "Have a major impact on (有重大影響)",
      "Lively and interactive (生動且互動的)",
      "Memorize grammar rules (背誦文法規則)",
      "Patiently encourage (耐心地鼓勵)",
      "Feel embarrassed (感到尷尬)",
      "Thanks to her guidance (多虧她的指導)",
      "Gradually build up (逐漸建立)",
      "Confidence in speaking (口說自信)",
      "Teach from the textbook (照本宣科)",
      "Western cultural stories (西方文化故事)",
      "Inspire someone to (啟發某人去...)",
      "Study abroad (留學)",
      "Role model (榜樣)",
      "Passionate about teaching (對教學有熱忱)",
      "Approachable (親切好接近的)",
      "Create a positive environment (創造正向環境)",
      "Give constructive feedback (給予建設性回饋)",
      "Patient listener (有耐心的傾聽者)",
      "Shape my character (塑造我的品格)"
    ]
  },
  {
    "number": 2,
    "category": "Describing People",
    "title": "2. Your best friend and explain why they are special t...",
    "prompt": "Describe your best friend and explain why they are special to you.",
    "model": "My best friend is my classmate, Kevin. We have known each other for three years since we entered junior high school. He is a very reliable and humorous person who always knows how to cheer me up when I am feeling down or stressed about exams. What makes him special is that we share many common interests, such as playing basketball and listening to Mandopop. Whenever I face challenges, he is always there to support me and offer great advice. I really treasure our friendship.",
    "keywords": [
      "Classmate (同學)",
      "Known each other (彼此認識)",
      "Reliable person (可靠的人)",
      "Humorous (幽默的)",
      "Cheer someone up (使某人高興起來)",
      "Feel down (心情低落)",
      "Stressed about exams (對考試感到壓力大)",
      "Share common interests (有共同興趣)",
      "Face challenges (面對挑戰)",
      "Support each other (互相支持)",
      "Offer great advice (提供棒的建議)",
      "Treasure our friendship (珍視我們的友誼)",
      "Through thick and thin (同甘共苦)",
      "Trustworthy (值得信賴的)",
      "Outgoing personality (外向的個性)",
      "Keep a secret (保守秘密)",
      "Hang out together (一起去晃晃)",
      "Get along well with (與...相處融洽)",
      "Count on someone (依靠某人)",
      "Kind-hearted (心腸好的)"
    ]
  },
  {
    "number": 3,
    "category": "Describing People",
    "title": "3. Famous person from history you would like to meet",
    "prompt": "Describe a famous person from history you would like to meet.",
    "model": "If I had the chance, I would really love to meet Mahatma Gandhi. He is an iconic historical figure known worldwide for leading India to independence through non-violent protests. I am truly fascinated by his peaceful philosophy and incredible determination. If I met him, I would ask him how he managed to stay calm and strong when facing such massive political pressure and danger. His life story teaches us that peaceful methods can be more powerful than violence, and I find that deeply inspiring.",
    "keywords": [
      "Had the chance (有機會的話)",
      "Iconic historical figure (指標性的歷史人物)",
      "Known worldwide for (以此聞名全世界)",
      "Independence (獨立)",
      "Non-violent protest (非暴力抗爭)",
      "Truly fascinated by (真正被...吸引)",
      "Peaceful philosophy (和平哲學)",
      "Incredible determination (驚人的決心)",
      "Manage to stay calm (設法保持冷靜)",
      "Face massive pressure (面對巨大的壓力)",
      "Political danger (政治危險)",
      "Deeply inspiring (深深啟發人的)",
      "Historical impact (歷史影響)",
      "Fight for justice (為正義而戰)",
      "Leadership skills (領導能力)",
      "Change the world (改變世界)",
      "Admire his courage (欽佩他的勇氣)",
      "Leave a legacy (留下精神遺產)",
      "Selfless leader (無私的領導者)",
      "Devote one's life to (奉獻一生給...)"
    ]
  },
  {
    "number": 4,
    "category": "Describing People",
    "title": "4. Family member you admire the most",
    "prompt": "Describe a family member you admire the most.",
    "model": "The family member I admire the most is my mother. She works a full-time job as an accountant, but she still manages to take excellent care of our family every day. She is incredibly hard-working and organized. No matter how tired she is after work, she always prepares nutritious dinners for us and listens to me talk about my day at school. From her, I have learned the importance of responsibility and time management. She is my ultimate role model in life.",
    "keywords": [
      "Admire the most (最欽佩)",
      "Full-time job (全職工作)",
      "Accountant (會計師)",
      "Manage to do something (設法做到某事)",
      "Take excellent care of (極佳地照顧)",
      "Incredibly hard-working (不可思議地勤奮)",
      "Well-organized (有條理的)",
      "No matter how tired (不管多累)",
      "Prepare nutritious dinners (準備營養的晚餐)",
      "Talk about my day (聊聊我的一天)",
      "Importance of responsibility (責任感的重要性)",
      "Time management (時間管理)",
      "Ultimate role model (終極榜樣)",
      "Express gratitude (表達感激)",
      "Unconditional love (無私的愛)",
      "Patient and kind (耐心且善良)",
      "Support my dreams (支持我的夢想)",
      "Balance work and family (平衡工作與家庭)",
      "Dedication (奉獻)",
      "Main pillar of the family (家庭的核心支柱)"
    ]
  },
  {
    "number": 5,
    "category": "Describing People",
    "title": "5. Successful person you know about and why they are s...",
    "prompt": "Describe a successful person you know about and why they are successful.",
    "model": "I want to describe Ang Lee, the world-famous film director from Taiwan. He is incredibly successful because he has won multiple Academy Awards for movies like 'Life of Pi.' In my opinion, his success comes from his unique ability to combine Eastern culture with Western storytelling techniques. Furthermore, he faced many failures and rejections early in his career, but he never gave up on his dream. His perseverance and passion for filmmaking are the main reasons why he achieved global success.",
    "keywords": [
      "World-famous (世界聞名的)",
      "Film director (電影導演)",
      "Incredibly successful (不可思議地成功的)",
      "Win multiple awards (贏得無數獎項)",
      "Academy Awards / Oscars (奧斯卡金像獎)",
      "In my opinion (依我之見)",
      "Unique ability (獨特的能力)",
      "Combine culture (融合文化)",
      "Storytelling techniques (敘事技巧)",
      "Face failures (面對失敗)",
      "Career rejections (職涯拒絕)",
      "Early in his career (在職涯早期)",
      "Never give up on (永不放棄)",
      "Perseverance (堅持不懈)",
      "Passion for filmmaking (對電影製作的熱忱)",
      "Achieve global success (取得全球性的成功)",
      "International recognition (國際認可)",
      "Overcome obstacles (克服障礙)",
      "Creative vision (創造性視野)",
      "Source of inspiration (靈感/啟發的來源)"
    ]
  },
  {
    "number": 6,
    "category": "Describing People",
    "title": "6. Neighbor who has helped you or your family",
    "prompt": "Describe a neighbor who has helped you or your family.",
    "model": "Our next-door neighbor, Mr. Wang, is a retired mechanic who is always willing to lend a helping hand. Last summer, during a heavy typhoon, our kitchen ceiling suddenly started leaking water. We were panicking because my parents weren't home. Mr. Wang noticed our situation, immediately came over with his tools, and quickly fixed the problem for us. He refused to take any money for it. Having a helpful and kind neighbor like him makes our community feel safe and warm.",
    "keywords": [
      "Next-door neighbor (隔壁鄰居)",
      "Retired mechanic (退休黑手/技工)",
      "Willing to lend a helping hand (樂意伸出援手)",
      "Heavy typhoon (強烈颱風)",
      "Kitchen ceiling (廚房天花板)",
      "Leak water (漏水)",
      "Panic (恐慌)",
      "Notice our situation (注意到我們的狀況)",
      "Immediately come over (立刻過來)",
      "Fix the problem (解決問題)",
      "Refuse to take money (拒絕拿錢)",
      "Helpful and kind (有幫助且善良的)",
      "Local community (當地社區)",
      "Sense of safety (安全感)",
      "Warm-hearted (熱心的)",
      "Good relationship (良好關係)",
      "Live close by (住得近)",
      "Emergency situation (緊急狀況)",
      "Do a favor (幫個忙)",
      "Trustworthy neighbor (值得信賴的鄰居)"
    ]
  },
  {
    "number": 7,
    "category": "Describing People",
    "title": "7. Artist, musician, or writer you like",
    "prompt": "Describe an artist, musician, or writer you like.",
    "model": "I am a big fan of the Taiwanese singer-songwriter Jay Chou. He is a brilliant musician who changed the Asian pop music industry completely. What I like most about him is his unique style, which blends traditional Chinese musical instruments with modern Western rap and R&B music. His songs always have beautiful melodies and meaningful lyrics that relate to teenage life and historical stories. Listening to his music helps me relax after studying hard, and his creativity constantly inspires me.",
    "keywords": [
      "Big fan of (是...的大粉絲)",
      "Singer-songwriter (創作歌手)",
      "Brilliant musician (才華橫溢的音樂家)",
      "Pop music industry (流行音樂產業)",
      "Unique style (獨特風格)",
      "Blend traditional elements (融合傳統元素)",
      "Chinese musical instruments (中國樂器)",
      "Modern Western rap (現代西方饒舌)",
      "Beautiful melodies (優美的旋律)",
      "Meaningful lyrics (有意義的歌詞)",
      "Relate to teenage life (與青少年生活產生共鳴)",
      "Relax after studying (讀書後放鬆)",
      "Constantly inspire (不斷啟發)",
      "Musical talent (音樂天賦)",
      "Catchy tunes (朗朗上口的曲調)",
      "Creative genius (創意天才)",
      "Pop icon (流行指標)",
      "Album release (專輯發行)",
      "Express emotions (表達情感)",
      "Perform on stage (在舞台上表演)"
    ]
  },
  {
    "number": 8,
    "category": "Describing People",
    "title": "8. Person you enjoy spending time with",
    "prompt": "Describe a person you enjoy spending time with.",
    "model": "I always enjoy spending time with my older cousin, Eric. He is currently studying engineering at university, so he is very knowledgeable and always tells me interesting facts about science and technology. We love playing video games together on weekends. He is an excellent listener and gives me great practical advice whenever I feel anxious about my upcoming exams or future high school life. Time always flies when we hang out because he is incredibly funny and easy to talk to.",
    "keywords": [
      "Enjoy spending time with (享受與...共度時光)",
      "Older cousin (堂/表哥)",
      "Study engineering (就讀工程)",
      "Knowledgeable (知識淵博的)",
      "Interesting facts (有趣的事實)",
      "Science and technology (科學與科技)",
      "Play video games (玩電子遊戲)",
      "On weekends (在週末)",
      "Excellent listener (極佳的傾聽者)",
      "Practical advice (實用的建議)",
      "Feel anxious about (對...感到焦慮)",
      "Upcoming exams (即將到來的考試)",
      "High school life (高中生活)",
      "Time flies (時間飛逝)",
      "Hang out (聚在一起/閒晃)",
      "Incredibly funny (非常搞笑的)",
      "Easy to talk to (好聊天的)",
      "Sense of humor (幽默感)",
      "Positive energy (正能量)",
      "Close relationship (親密的關係)"
    ]
  },
  {
    "number": 9,
    "category": "Describing Places",
    "title": "9. Your favorite room in your house",
    "prompt": "Describe your favorite room in your house.",
    "model": "My favorite room in my house is definitely my bedroom. It is my personal sanctuary where I can fully relax and be myself. The walls are painted a soothing light blue, and there is a large window that lets in plenty of natural sunlight during the day. In the corner, I have a comfortable desk where I do my homework and read books. I have also decorated the walls with posters of my favorite anime characters. It is the perfect place for me to unwind after a tiring day at school.",
    "keywords": [
      "Favorite room (最喜歡的房間)",
      "Definitely (肯定地)",
      "Personal sanctuary (個人聖地/避風港)",
      "Fully relax (完全放鬆)",
      "Painted a soothing color (粉刷了舒緩的顏色)",
      "Large window (大窗戶)",
      "Natural sunlight (自然陽光)",
      "In the corner (在角落)",
      "Comfortable desk (舒適的書桌)",
      "Do my homework (做功課)",
      "Read books (看書)",
      "Decorate the walls (裝飾牆壁)",
      "Favorite anime characters (最喜歡的動漫角色)",
      "Perfect place to unwind (放鬆的完美地方)",
      "Tiring day at school (學校累人的一天)",
      "Cozy bed (舒適的床)",
      "Private space (隱私空間)",
      "Keep things organized (保持物品整潔)",
      "Peaceful atmosphere (和平/安計的氣氛)",
      "Feel safe and comfortable (感到安全與舒適)"
    ]
  },
  {
    "number": 10,
    "category": "Describing Places",
    "title": "10. Famous tourist attraction in your country",
    "prompt": "Describe a famous tourist attraction in your country.",
    "model": "A famous tourist attraction in Taiwan that I highly recommend is Taipei 101. Located in the heart of Taipei City, it was once the tallest building in the world. It looks like a giant bamboo stalk, which symbolizes strength and growth in Asian culture. Visitors can take a super-fast elevator to the indoor observation deck on the 89th floor. From there, you can get a spectacular panoramic view of the entire city. It is especially beautiful at night when the city lights up.",
    "keywords": [
      "Tourist attraction (觀光景點)",
      "Highly recommend (強力推薦)",
      "Located in the heart of (位於...的心臟地帶)",
      "Tallest building (最高建築)",
      "Giant bamboo stalk (巨大的竹節)",
      "Symbolize strength (象徵力量)",
      "Asian culture (亞洲文化)",
      "Super-fast elevator (超高速電梯)",
      "Indoor observation deck (室內觀景台)",
      "Spectacular panoramic view (壯觀的全景)",
      "Entire city (整個城市)",
      "Especially beautiful at night (夜間特別美麗)",
      "City lights up (城市亮起燈火)",
      "Architectural marvel (建築奇蹟)",
      "Shopping mall (購物中心)",
      "Landmark of Taiwan (台灣地標)",
      "Attract millions of visitors (吸引數百萬遊客)",
      "New Year fireworks (跨年煙火)",
      "Urban landscape (城市景觀)",
      "Must-visit place (必訪之地)"
    ]
  },
  {
    "number": 11,
    "category": "Describing Places",
    "title": "11. Beautiful park or natural place you have visited",
    "prompt": "Describe a beautiful park or natural place you have visited.",
    "model": "One of the most beautiful natural places I have visited is Taroko Gorge in Hualien. It is famous for its stunning marble canyons, rushing rivers, and high mountains. When I walked along the trails, I was amazed by the breathtaking scenery created by nature over millions of years. The air there was incredibly fresh and crisp, which made me feel deeply refreshed. It is an ideal escape from the noisy city life, and it taught me to appreciate the wonders of nature.",
    "keywords": [
      "Natural place (自然景點)",
      "Marble canyons (大理石峽谷)",
      "Rushing rivers (奔騰的河流)",
      "High mountains (高山)",
      "Walk along the trails (沿著步道散步)",
      "Amazed by (對...感到驚艷)",
      "Breathtaking scenery (美到令人窒息的風景)",
      "Created by nature (大自然創造的)",
      "Incredibly fresh and crisp air (新鮮乾淨空氣)",
      "Feel deeply refreshed (感到深受洗滌)",
      "Ideal escape (理想的逃離/避風港)",
      "Noisy city life (嘈雜的城市生活)",
      "Appreciate nature (欣賞大自然)",
      "Wonders of nature (大自然的奇蹟)",
      "Spectacular views (壯觀景色)",
      "Hiking route (健行路線)",
      "Geological features (地質特徵)",
      "National park (國家公園)",
      "Peaceful environment (寧靜的環境)",
      "Take photos (拍照)"
    ]
  },
  {
    "number": 12,
    "category": "Describing Places",
    "title": "12. School or library where you like to study",
    "prompt": "Describe a school or library where you like to study.",
    "model": "I enjoy studying at the New Taipei City Public Library. It is a modern, multi-story building with excellent facilities. The study areas are extremely quiet and well-lit, which helps me focus entirely on my textbooks without any distractions. There are comfortable individual desks and free Wi-Fi access for research. Additionally, they have a massive collection of English books, which is helpful for my preparation to study in Singapore. It is definitely my favorite environment for productive learning.",
    "keywords": [
      "Public library (公共圖書館)",
      "Modern building (現代建築)",
      "Multi-story (多層樓的)",
      "Excellent facilities (優秀的設施)",
      "Quiet environment (安靜的環境)",
      "Well-lit (採光良好的)",
      "Focus entirely on (完全專注於)",
      "Without distractions (毫無干擾)",
      "Individual desks (獨立書桌)",
      "Free Wi-Fi access (免費網路使用)",
      "Massive collection (巨大的館藏)",
      "Study in Singapore (在新加坡讀書)",
      "Favorite environment (最喜歡的環境)",
      "Productive learning (有效率的學習)",
      "Borrow books (借書)",
      "Academic research (學術研究)",
      "Open to the public (對公眾開放)",
      "Strict quiet policy (嚴格的安靜規定)",
      "Comfortable seating (舒適的座位)",
      "Expand knowledge (擴展知識)"
    ]
  },
  {
    "number": 13,
    "category": "Describing Places",
    "title": "13. Interesting city or town you would like to visit in...",
    "prompt": "Describe an interesting city or town you would like to visit in the future.",
    "model": "In the future, I would love to visit Singapore. As an international hub, it is famous for blending modern skyscrapers with lush green gardens, earning it the nickname 'City in a Garden.' I am particularly eager to visit the Marina Bay Sands and the famous Gardens by the Bay to see the giant Supertrees. Furthermore, since Singapore is a multicultural society, I want to try various delicious foods from different cultures, like chicken rice and laksa. It seems like an ideal place to experience both urban growth and nature.",
    "keywords": [
      "Future travel (未來的旅行)",
      "International hub (國際樞紐/中心)",
      "Blend skyscrapers (融合摩天大樓)",
      "Lush green gardens (鬱鬱蔥蔥的花園)",
      "Nickname (綽號)",
      "Particularly eager to (特別渴望去...)",
      "Multicultural society (多元文化社會)",
      "Various delicious foods (各種美味食物)",
      "Different cultures (不同的文化)",
      "Urban growth (都市發展)",
      "Experience nature (體驗大自然)",
      "Public transport system (大眾運輸系統)",
      "Clean and safe (乾淨且安全)",
      "Famous landmark (著名地標)",
      "Advanced city (先進城市)",
      "Local delicacies (在地美食)",
      "English-speaking environment (英語環境)",
      "Tourist destination (旅遊目的地)",
      "Futuristic architecture (未來感建築)",
      "Broaden my horizons (開闊我的視野)"
    ]
  },
  {
    "number": 14,
    "category": "Describing Places",
    "title": "14. Restaurant or cafe that you enjoy going to",
    "prompt": "Describe a restaurant or cafe that you enjoy going to.",
    "model": "I love going to a cozy coffee shop near my school called 'The Green Corner.' It has a warm atmosphere with soft acoustic music playing in the background, making it perfect for relaxing. They serve delicious homemade waffles and high-quality milk tea. The staff are always friendly and welcoming. I often go there with my classmates on Friday afternoons to chat about our week and relieve our academic stress. It is a wonderful neighborhood spot with great vibes.",
    "keywords": [
      "Cozy coffee shop (溫馨的咖啡廳)",
      "Warm atmosphere (溫暖的氣氛)",
      "Soft acoustic music (柔和的原音音樂)",
      "Background music (背景音樂)",
      "Perfect for relaxing (適合放鬆)",
      "Serve delicious food (供應美食)",
      "Homemade waffles (手工鬆餅)",
      "High-quality milk tea (高品質奶茶)",
      "Friendly staff (親切的店員)",
      "Welcoming (令人感到受歡迎的)",
      "Friday afternoons (週五下午)",
      "Chat about our week (聊聊我們的一週)",
      "Relieve academic stress (紓解課業壓力)",
      "Neighborhood spot (社區小店)",
      "Great vibes (棒的氛圍)",
      "Reasonable prices (價格合理)",
      "Comfort food (療癒食物)",
      "Beautifully decorated (裝飾精美的)",
      "Regular customer (熟客)",
      "Hang out with friends (跟朋友相聚)"
    ]
  },
  {
    "number": 15,
    "category": "Describing Places",
    "title": "15. Place where you go to exercise or play sports",
    "prompt": "Describe a place where you go to exercise or play sports.",
    "model": "I regularly go to the sports center near my house to play badminton and basketball. It is a modern facility equipped with indoor courts, a swimming pool, and a fully functional gym. I prefer exercising there because the indoor courts protect us from bad weather like rain or extreme summer heat. Playing sports there with my friends twice a week helps me stay healthy and physically fit. It is an energetic place filled with active people, which motivates me to exercise harder.",
    "keywords": [
      "Regularly go to (定期去)",
      "Sports center (運動中心)",
      "Play badminton (打羽毛球)",
      "Modern facility (現代化設施)",
      "Equipped with (配備有...)",
      "Indoor courts (室內球場)",
      "Swimming pool (游泳池)",
      "Fully functional gym (功能齊全的健身房)",
      "Prefer exercising (更喜歡運動)",
      "Protect from bad weather (免受壞天氣影響)",
      "Extreme summer heat (夏季酷熱)",
      "Twice a week (一週兩次)",
      "Stay healthy (保持健康)",
      "Physically fit (身體結實/健康)",
      "Energetic place (活力充沛的地方)",
      "Active people (活躍/運動的人)",
      "Motivate someone to (激勵某人去...)",
      "Exercise harder (更努力運動)",
      "Workout routine (健身規律)",
      "Team sports (團隊運動)"
    ]
  },
  {
    "number": 16,
    "category": "Describing Objects / Possessions",
    "title": "16. Important electronic device you use every day",
    "prompt": "Describe an important electronic device you use every day.",
    "model": "The electronic device I use daily is my smartphone. It is an indispensable tool for my life and studies. I use it for multiple purposes, such as looking up English definitions, communicating with my classmates via messaging apps, and checking bus schedules. Additionally, it has useful educational apps that help me practice my English listening skills. Although it can sometimes be a distraction, it is incredibly convenient and keeps me connected with my family and the rest of the world.",
    "keywords": [
      "Electronic device (電子裝置)",
      "Indispensable tool (不可或缺的工具)",
      "Multiple purposes (多種用途)",
      "Look up definitions (查定義/查單字)",
      "Communicate with classmates (與同學溝通)",
      "Messaging apps (通訊軟體)",
      "Check bus schedules (查公車時刻表)",
      "Educational apps (教育應用程式)",
      "Practice listening skills (練習聽力技巧)",
      "Source of distraction (分心的來源)",
      "Incredibly convenient (不可思議地方便)",
      "Keep connected (保持聯絡)",
      "Smart technology (智慧科技)",
      "Portable (便攜的)",
      "Search for information (搜尋資訊)",
      "Stay updated (保持最新消息)",
      "High-resolution screen (高解析度螢幕)",
      "Battery life (電池壽命)",
      "Digital age (數位時代)",
      "Essential item (必需品)"
    ]
  },
  {
    "number": 17,
    "category": "Describing Objects / Possessions",
    "title": "17. Gift you received that is very meaningful to you",
    "prompt": "Describe a gift you received that is very meaningful to you.",
    "model": "On my graduation from elementary school, my grandfather gave me a beautiful, classic fountain pen. It is made of black resin with gold trim, and my name is engraved on it. This gift is meaningful because my grandfather passed away last year, so the pen serves as a precious keepsake. Whenever I use it to write in my journal, I feel connected to his love and wisdom. It reminds me to work hard and stay honest, just like he always taught me.",
    "keywords": [
      "Gift received (收到的禮物)",
      "Meaningful (有意義的)",
      "Graduation (畢業)",
      "Classic fountain pen (經典鋼筆)",
      "Engraved name (刻了名字)",
      "Passed away (過世)",
      "Precious keepsake (珍貴的紀念物)",
      "Write in my journal (寫日記)",
      "Connected to his love (與他的愛連結)",
      "Remind someone to (提醒某人去...)",
      "Work hard (努力工作/讀書)",
      "Stay honest (保持誠實)",
      "Generous present (慷慨的禮物)",
      "Family memory (家庭回憶)",
      "Highly valued (高度珍視的)",
      "Emotional value (情感價值)",
      "Take care of it (好好照顧它)",
      "Special occasion (特殊場合)",
      "Wisdom (智慧)",
      "Express affection (表達情感)"
    ]
  },
  {
    "number": 18,
    "category": "Describing Objects / Possessions",
    "title": "18. Piece of clothing you like to wear most",
    "prompt": "Describe a piece of clothing you like to wear most.",
    "model": "My favorite piece of clothing is an oversized denim jacket that I bought during a vacation last year. It has a slightly faded blue color and a very casual, stylish look. I love wearing it because it is incredibly versatile and goes well with almost any outfit, whether I am wearing a T-shirt or a hoodie. Most importantly, it is extremely comfortable and protects me from the chilly wind on autumn mornings. Wearing it makes me feel confident and relaxed.",
    "keywords": [
      "Piece of clothing (一件衣服)",
      "Oversized denim jacket (寬鬆牛仔外套)",
      "Bought during vacation (在度假時買的)",
      "Faded blue color (褪色藍)",
      "Casual look (休閒風格)",
      "Stylish (時尚有型)",
      "Incredibly versatile (不可思議地百搭)",
      "Go well with (與...很配)",
      "Outfit (全套服裝)",
      "Hoodie (帽T)",
      "Extremely comfortable (極其舒適)",
      "Protect from chilly wind (抵禦寒風)",
      "Autumn mornings (秋天早晨)",
      "Feel confident (感到自信)",
      "Personal style (個人風格)",
      "Durable material (耐用的材質)",
      "Fashion choice (時尚選擇)",
      "Practical wear (實穿)",
      "Wardrobe favorite (衣櫃最愛)",
      "Everyday clothes (日常便服)"
    ]
  },
  {
    "number": 19,
    "category": "Describing Objects / Possessions",
    "title": "19. Book that you found interesting or useful",
    "prompt": "Describe a book that you found interesting or useful.",
    "model": "A book that I found highly useful is called 'Atomic Habits' by James Clear. It explains how making tiny changes in our daily routines can lead to massive life improvements over time. I read it during my summer break, and it completely changed how I manage my schedule. Thanks to its practical advice, I managed to build a habit of studying English vocabulary for fifteen minutes every night. It taught me that consistency is the key to achieving any long-term goal.",
    "keywords": [
      "Found highly useful (覺得非常實用)",
      "Atomic Habits (原子習慣)",
      "Tiny changes (微小的改變)",
      "Daily routines (日常慣例)",
      "Massive improvements (巨大的進步)",
      "Over time (久而久之)",
      "Summer break (暑假)",
      "Manage my schedule (管理我的行程)",
      "Practical advice (實用建議)",
      "Build a habit (建立習慣)",
      "English vocabulary (英文單字)",
      "Every night (每晚)",
      "Consistency is key (持之以恆是關鍵)",
      "Long-term goal (長期目標)",
      "Life-changing book (改變人生的書)",
      "Best-seller (暢銷書)",
      "Easy to understand (易懂的)",
      "Highly recommended (強烈推薦)",
      "Self-improvement (自我提升)",
      "Productive mindset (高效率的心態)"
    ]
  },
  {
    "number": 20,
    "category": "Describing Objects / Possessions",
    "title": "20. Website or mobile application you use to learn new...",
    "prompt": "Describe a website or mobile application you use to learn new things.",
    "model": "I frequently use Duolingo, a language learning application, to improve my English and explore basic Spanish. The app is designed like a game, where you can earn points and level up by completing quick lessons. This playful setup makes learning grammar and vocabulary highly entertaining rather than boring. It also tracks my daily progress, which motivates me to keep a consistent study streak. It is an amazing educational tool for students to utilize during short breaks.",
    "keywords": [
      "Frequently use (頻繁使用)",
      "Language learning application (語言學習App)",
      "Improve English (進步英文)",
      "Explore basic skills (探索基本技巧)",
      "Designed like a game (設計成像遊戲)",
      "Earn points (贏得分數)",
      "Level up (升級)",
      "Quick lessons (快速單元課程)",
      "Playful setup (好玩的設定)",
      "Highly entertaining (極具娛樂性的)",
      "Rather than boring (而不是枯燥的)",
      "Track daily progress (追蹤每日進度)",
      "Consistent study streak (持續的讀書紀錄)",
      "Educational tool (教育工具)",
      "Utilize during breaks (利用休息時間)",
      "User-friendly interface (使用者友善界面)",
      "Free interactive lessons (免費互動課程)",
      "Expand vocabulary (擴展字彙)",
      "Daily notification (每日提醒通知)",
      "Digital learning (數位學習)"
    ]
  },
  {
    "number": 21,
    "category": "Describing Objects / Possessions",
    "title": "21. Piece of art or decoration in your home that you like",
    "prompt": "Describe a piece of art or decoration in your home that you like.",
    "model": "In our living room, there is a large framed landscape painting hanging on the central wall. It depicts a peaceful countryside scene with green fields, mountains, and a clear blue sky. My parents bought it from a local artist during our trip to Yilan. I love looking at it because the soft colors give me a sense of peace and tranquility whenever I feel stressed out about my studies. It adds a touch of natural beauty and elegance to our living space.",
    "keywords": [
      "Living room (客廳)",
      "Framed landscape painting (有框的風景畫)",
      "Hanging on the wall (掛在牆上)",
      "Depict a peaceful scene (描繪平靜的畫面)",
      "Countryside scene (鄉村風景)",
      "Local artist (當地藝術家)",
      "Family trip (家族旅行)",
      "Soft colors (柔和的顏色)",
      "Sense of peace (和平感)",
      "Tranquility (寧靜)",
      "Stressed out about studies (因學業感到壓力大)",
      "Add a touch of (增添了一抹...)",
      "Natural beauty (自然美)",
      "Elegance (優雅)",
      "Living space (居住空間)",
      "Interior decoration (室內裝飾)",
      "Visual appeal (視覺吸引力)",
      "Art lover (藝術愛好者)",
      "Relaxing effect (放鬆的效果)",
      "Masterpiece (傑作)"
    ]
  },
  {
    "number": 22,
    "category": "Describing Objects / Possessions",
    "title": "22. Object that is typical or traditional in your culture",
    "prompt": "Describe an object that is typical or traditional in your culture.",
    "model": "A traditional object in Taiwanese culture is the pineapple cake. It is a famous pastry filled with sweet pineapple paste wrapped in a rich, buttery crust. In Taiwanese Hokkien, the word for pineapple sounds like 'prosperity arrives,' which makes it a highly popular symbol of good luck and fortune. People usually give them as gifts during major festivals, like the Lunar New Year, to wish others success. It represents our warm hospitality and deep cultural heritage.",
    "keywords": [
      "Traditional object (傳統物品)",
      "Taiwanese culture (台灣文化)",
      "Pineapple cake (鳳梨酥)",
      "Famous pastry (著名的糕點)",
      "Rich, buttery crust (濃郁奶香的外皮)",
      "Sound like prosperity (音同「旺來」象徵繁榮)",
      "Popular symbol (受歡迎的象徵)",
      "Good luck and fortune (好運與財富)",
      "Give as gifts (作為禮物贈送)",
      "Major festivals (重大節日)",
      "Lunar New Year (農曆新年)",
      "Wish others success (祝他人成功)",
      "Warm hospitality (溫暖的款待)",
      "Deep cultural heritage (深厚的文化遺產)",
      "Local delicacy (地方美食)",
      "Souvenir (紀念品)",
      "Traditional recipe (傳統食譜)",
      "Deeply rooted in (深植於...)",
      "Bring blessings (帶來祝福)",
      "Sweet paste filling (甜的內餡)"
    ]
  },
  {
    "number": 23,
    "category": "Describing Events / Personal Experiences",
    "title": "23. Memorable school trip you took",
    "prompt": "Describe a memorable school trip you took.",
    "model": "The most memorable school trip I took was our graduation trip to Kenting last year. We spent three days exploring the beautiful beaches and night markets with our classmates. The highlight of the trip was visiting the national aquarium, where we slept overnight under a giant glass tunnel surrounded by sharks and tropical fish. It was an incredible experience because we stayed up late talking and strengthening our friendships. It was the perfect ending to my junior high school life.",
    "keywords": [
      "Memorable school trip (難忘的校外教學)",
      "Graduation trip (畢業旅行)",
      "Spend three days (度過三天)",
      "Explore beaches (探索海灘)",
      "Night markets (夜市)",
      "Highlight of the trip (旅程最棒的部分)",
      "National aquarium (國家海生館)",
      "Sleep overnight (過夜)",
      "Giant glass tunnel (巨大玻璃隧道)",
      "Surrounded by sharks (被鯊魚圍繞)",
      "Tropical fish (熱帶魚)",
      "Incredible experience (不可思議的體驗)",
      "Stay up late (熬夜)",
      "Strengthen friendships (加深友誼)",
      "Perfect ending (完美的結局)",
      "Junior high school life (國中生活)",
      "Unforgettable memories (難忘的回記)",
      "Travel by bus (搭巴士旅行)",
      "Tour guide (導遊)",
      "Bond with classmates (與同學建立深厚感情)"
    ]
  },
  {
    "number": 24,
    "category": "Describing Events / Personal Experiences",
    "title": "24. Festival or holiday celebration in your country",
    "prompt": "Describe a festival or holiday celebration in your country.",
    "model": "My favorite holiday celebration in Taiwan is the Mid-Autumn Festival. It is a traditional festival where family members gather together under the full moon. The most popular activities include having an outdoor barbecue, eating sweet mooncakes, and sharing pomelos. Children often wear the pomelo skins as hats for fun. For me, this festival is extremely special because it highlights the cultural value of family reunion, allowing us to catch up and enjoy quality time together.",
    "keywords": [
      "Holiday celebration (節日慶祝)",
      "Mid-Autumn Festival (中秋節)",
      "Traditional festival (傳統節日)",
      "Gather together (聚集在一起)",
      "Full moon (滿月)",
      "Outdoor barbecue (戶外烤肉)",
      "Eat mooncakes (吃月餅)",
      "Share pomelos (分享柚子)",
      "Wear pomelo skins (戴柚子皮)",
      "Extremely special (極其特別)",
      "Highlight cultural values (凸顯文化價值)",
      "Family reunion (家庭團聚)",
      "Catch up (聚舊/聊近況)",
      "Enjoy quality time (享受優質時光)",
      "Festive atmosphere (節日氣氛)",
      "Seasonal food (時令食物)",
      "Pass down traditions (傳承傳統)",
      "Public holiday (國定假日)",
      "Express love for family (表達對家人的愛)",
      "Joyful occasion (快樂的場合)"
    ]
  },
  {
    "number": 25,
    "category": "Describing Events / Personal Experiences",
    "title": "25. Important accomplishment you achieved",
    "prompt": "Describe an important accomplishment you achieved.",
    "model": "An important accomplishment I achieved was winning first place in our school's English speech contest last semester. Initially, I was terrified of public speaking and had a weak English accent. To prepare, I practiced in front of a mirror every single day for a month and recorded my voice to correct pronunciation errors. Winning the award was an unforgettable moment because it proved that my hard work paid off. It significantly boosted my self-confidence and motivation to master English.",
    "keywords": [
      "Important accomplishment (重要成就)",
      "Win first place (贏得第一名)",
      "Speech contest (演講比賽)",
      "Last semester (上學期)",
      "Terrified of public speaking (對公開演講感到恐懼)",
      "Weak accent (弱的口音)",
      "In front of a mirror (在鏡子前面)",
      "Every single day (每一天)",
      "Record my voice (錄下我的聲音)",
      "Correct errors (糾正錯誤)",
      "Pronunciation (發音)",
      "Unforgettable moment (難忘的時刻)",
      "Hard work paid off (努力得到了回報)",
      "Significantly boosted (顯著提升了)",
      "Self-confidence (自信心)",
      "Motivation to learn (學習動力)",
      "Master a language (精通一種語言)",
      "Overcome fear (克服恐懼)",
      "Feel proud of (為...感到驕傲)",
      "Achieve a goal (達成目標)"
    ]
  },
  {
    "number": 26,
    "category": "Describing Events / Personal Experiences",
    "title": "26. Event where you had a disagreement with someone and...",
    "prompt": "Describe an event where you had a disagreement with someone and how you solved it.",
    "model": "During a group project last month, my classmate and I had a severe disagreement about our presentation topic. He wanted to focus on history, while I preferred technology. We were stuck and the deadline was approaching quickly. To solve this conflict, I suggested that we sit down and list the pros and cons of both ideas. Eventually, we found a creative compromise by presenting the history of modern technology. This experience taught me the importance of active listening and teamwork.",
    "keywords": [
      "Group project (小組報告/專案)",
      "Severe disagreement (嚴重的意見分歧)",
      "Presentation topic (簡報主題)",
      "Focus on history (專注於歷史)",
      "Prefer technology (更喜歡科技)",
      "Stuck (卡住/僵持不下)",
      "Deadline was approaching (截止日期接近中)",
      "Solve a conflict (解決衝突)",
      "Suggest an idea (提議一個點子)",
      "Pros and cons (優缺點)",
      "Creative compromise (有創意的折衷辦法)",
      "Active listening (積極傾聽)",
      "Teamwork (團隊合作)",
      "Communication skills (溝通技巧)",
      "Find a solution (找到解決方法)",
      "Express opinions calmly (冷靜表達意見)",
      "Respect differences (尊重差異)",
      "Reach an agreement (達成協議)",
      "Work together smoothly (順暢地一起工作)",
      "Valuable lesson (寶貴的一課)"
    ]
  },
  {
    "number": 27,
    "category": "Describing Events / Personal Experiences",
    "title": "27. Time when you helped a stranger",
    "prompt": "Describe a time when you helped a stranger.",
    "model": "A few weeks ago, while waiting at a busy train station, I saw an elderly foreign tourist looking confused and staring blankly at a ticket machine. Realizing he couldn't read the Chinese characters, I gathered my courage and approached him in English. I politely asked if he needed assistance and guided him step-by-step to buy the correct train ticket to Hualien. He smiled warmly and thanked me sincerely. Helping him made me feel incredibly proud and proved my English was useful.",
    "keywords": [
      "Busy train station (繁忙的火車站)",
      "Elderly foreign tourist (年長的國外遊客)",
      "Look confused (看起來困惑)",
      "Stare blankly (茫然地盯著看)",
      "Ticket machine (售票機)",
      "Chinese characters (中文字)",
      "Gather my courage (鼓起勇氣)",
      "Approach someone (走近某人)",
      "Need assistance (需要協助)",
      "Guide step-by-step (一步步引導)",
      "Smile warmly (溫暖地微笑)",
      "Thank sincerely (真誠地感謝)",
      "Feel incredibly proud (感到無比自豪)",
      "Useful language (有用的語言)",
      "Lend a hand (伸出援手)",
      "Act of kindness (善行)",
      "Commute (通勤)",
      "Cross cultural communication (跨文化溝通)",
      "Make someone's day (讓某人開心的一天)",
      "Friendly interaction (友善的互動)"
    ]
  },
  {
    "number": 28,
    "category": "Describing Events / Personal Experiences",
    "title": "28. Happy childhood memory",
    "prompt": "Describe a happy childhood memory.",
    "model": "One of my happiest childhood memories is learning how to ride a bicycle with my father at a local park when I was eight years old. Initially, I kept falling off and scraping my knees, which made me want to cry and give up. However, my father stayed patient, held the back of my seat, and kept cheering me on. Suddenly, I noticed he let go and I was riding smoothly by myself! I felt an incredible sense of freedom and pure joy that I will always remember.",
    "keywords": [
      "Childhood memory (童年回憶)",
      "Ride a bicycle (騎腳踏車)",
      "Local park (當地公園)",
      "Eight years old (八歲)",
      "Keep falling off (不斷跌倒)",
      "Scrape knees (擦傷膝蓋)",
      "Want to cry (想哭)",
      "Give up (放棄)",
      "Stay patient (保持耐心)",
      "Hold the back of the seat (扶著坐墊後方)",
      "Cheer someone on (為某人加油)",
      "Let go (放手)",
      "Ride smoothly (順暢地騎)",
      "By myself (靠我自己)",
      "Sense of freedom (自由感)",
      "Pure joy (純粹的快樂)",
      "Precious time (珍貴時光)",
      "Support from family (家人的支持)",
      "Overcome a difficulty (克服困難)",
      "Grow up (長大)"
    ]
  },
  {
    "number": 29,
    "category": "Describing Events / Personal Experiences",
    "title": "29. New hobby or activity you tried recently",
    "prompt": "Describe a new hobby or activity you tried recently.",
    "model": "Recently, I started learning how to cook basic Western dishes, like pasta and scrambled eggs, through YouTube tutorials. I decided to try this activity because I want to be independent when I move to Singapore for school. At first, my dishes were either too salty or burnt, but after practicing multiple times, my skills improved significantly. Preparing my own meals gives me a great sense of control and creativity, and it has turned into a deeply relaxing hobby.",
    "keywords": [
      "Tried recently (最近嘗試的)",
      "New hobby (新嗜好)",
      "Cook basic dishes (煮基本料理)",
      "Western food (西方食物)",
      "YouTube tutorials (網路影片教學)",
      "Independent (獨立的)",
      "Move abroad (搬去國外)",
      "Too salty (太鹹)",
      "Burnt food (燒焦的食物)",
      "Practice multiple times (練習很多次)",
      "Improve significantly (顯著進步)",
      "Prepare own meals (自己做飯)",
      "Sense of control (掌控感)",
      "Creative activity (有創意的活動)",
      "Relaxing hobby (放鬆的嗜好)",
      "Culinary skills (烹飪技巧)",
      "Kitchen safety (廚房安全)",
      "Trial and error (嘗試與錯誤)",
      "Healthy lifestyle (健康的生活方式)",
      "Satisfying result (令人滿意的結果)"
    ]
  },
  {
    "number": 30,
    "category": "Describing Events / Personal Experiences",
    "title": "30. Time when you had to adapt to a sudden change",
    "prompt": "Describe a time when you had to adapt to a sudden change.",
    "model": "Two years ago, during the pandemic, our school suddenly shifted entirely to online learning from home. It was a massive change because I had to adapt to using digital platforms like Zoom and Google Classroom overnight. Initially, I struggled with technical glitches and experienced difficulty staying focused without teachers being physically present. To cope, I created a strict daily schedule and set up a quiet study zone in my room. This experience helped me become a highly self-disciplined and adaptable person.",
    "keywords": [
      "Adapt to change (適應改變)",
      "Sudden change (突然的改變)",
      "Pandemic period (疫情期間)",
      "Shift to online learning (轉向線上學習)",
      "Digital platforms (數位平台)",
      "Google Classroom (谷歌教室)",
      "Overnight (一夜之間)",
      "Struggle with glitches (與系統故障搏鬥)",
      "Technical issues (技術問題)",
      "Experience difficulty (經歷困難)",
      "Stay focused (保持專注)",
      "Physically present (實體在場的)",
      "Cope with problems (應對問題)",
      "Create a strict schedule (建立時間表)",
      "Quiet study zone (安靜的讀書區)",
      "Self-disciplined (自律的)",
      "Adaptable person (適應力強的人)",
      "Virtual classroom (虛擬教室)",
      "Independent study (獨立學習)",
      "Overcome challenges (克服挑戰)"
    ]
  },
  {
    "number": 31,
    "category": "Social Media & Digital Life",
    "title": "31. Talk about what you usually do when you browse soci...",
    "prompt": "Talk about what you usually do when you browse social media.",
    "model": "When I browse social media platforms like Instagram or Threads, I mostly use them to stay connected with my classmates and see what they are up to. I enjoy viewing my friends' daily stories and sharing funny memes with them. Additionally, I follow several educational accounts that share quick English slang tips, which is quite helpful for my upcoming studies abroad. I also use social media to follow news about my favorite Mandopop singers. It is a relaxing way for me to unwind and catch up on trends after a long day of schoolwork.",
    "keywords": [
      "Browse social media (瀏覽社群媒體)",
      "Stay connected with (與...保持聯絡)",
      "See what they are up to (看他們在忙什麼)",
      "Daily stories (日常限時動態)",
      "Share funny memes (分享搞笑迷因)",
      "Follow accounts (追蹤帳號)",
      "Educational accounts (教育類帳號)",
      "English slang tips (英文俚語訣竅)",
      "Upcoming studies abroad (海外留學)",
      "Follow news (關注新聞/消息)",
      "Catch up on trends (跟上潮流)",
      "Unwind after school (放學後放鬆)",
      "Scroll through my feed (刷動態)",
      "Direct message (私訊)",
      "User engagement (用戶互動)",
      "Post updates (發布近況)",
      "Stay informed (保持消息靈通)",
      "Online community (網路社群)",
      "Passive entertainment (被動娛樂)",
      "Digital footprint (數位足跡)"
    ]
  },
  {
    "number": 32,
    "category": "Social Media & Digital Life",
    "title": "32. Discuss your thoughts on social media addiction amo...",
    "prompt": "Discuss your thoughts on social media addiction among teenagers.",
    "model": "In my opinion, social media addiction is a serious problem for many teenagers today. Many of my classmates spend hours scrolling through short videos on TikTok or Instagram instead of studying or sleeping. This habit often leads to poor time management and bad grades at school. Furthermore, constantly comparing our real lives to other people's perfect online profiles can make us feel anxious and insecure. I believe we need to set strict daily screen time limits to maintain a healthy balance between our digital lives and reality.",
    "keywords": [
      "Social media addiction (社群媒體成癮)",
      "Serious problem (嚴重問題)",
      "Spend hours scrolling (花時間刷螢幕)",
      "Short videos (短影音)",
      "Instead of studying (而不是讀書)",
      "Poor time management (糟糕的時間管理)",
      "Bad grades (爛成績)",
      "Constantly compare (不斷比較)",
      "Perfect online profiles (完美的網路檔案)",
      "Feel anxious (感到焦慮)",
      "Insecure (沒有安全感的)",
      "Screen time limits (螢幕時間限制)",
      "Maintain a healthy balance (保持健康平衡)",
      "Digital life (數位生活)",
      "Peer pressure (同儕壓力)",
      "Lose track of time (忘記時間)",
      "Mental health (心理健康)",
      "Real-world interaction (現實世界互動)",
      "Notification alerts (通知鈴聲/警示)",
      "Self-discipline (自律)"
    ]
  },
  {
    "number": 33,
    "category": "Social Media & Digital Life",
    "title": "33. Your favorite social media platform and why you pre...",
    "prompt": "Describe your favorite social media platform and why you prefer it.",
    "model": "My favorite social media platform is Instagram because it focuses heavily on visual content like photos and short videos. I prefer it over other platforms because the user interface is clean, simple, and very easy to navigate. It allows me to express my creativity by posting photos of my daily life, delicious food, and family trips. I also love using the 'Close Friends' feature, which lets me share private moments with only my trusted classmates. It makes me feel safe while staying socially active online.",
    "keywords": [
      "Favorite platform (最喜歡的平台)",
      "Focus heavily on (非常專注於...)",
      "Visual content (視覺內容)",
      "User interface (使用者介面)",
      "Easy to navigate (易於操作/瀏覽)",
      "Express creativity (表達創意)",
      "Post photos (發布照片)",
      "Close Friends feature (摯友功能)",
      "Share private moments (分享私密時刻)",
      "Trusted classmates (信任的同學)",
      "Stay socially active (保持社交活躍)",
      "Online privacy (網路隱私)",
      "Photo-sharing app (相片分享應用程式)",
      "Stay in touch (保持聯絡)",
      "Highly engaging (極具吸引力的)",
      "Direct messaging (即時私訊)",
      "Customize my profile (自訂個人檔案)",
      "Follow trends (跟隨潮流)",
      "Digital communication (數位溝通)",
      "Positive vibes (正向氛圍)"
    ]
  },
  {
    "number": 34,
    "category": "Social Media & Digital Life",
    "title": "34. Experience where you decided to take a break from s...",
    "prompt": "Describe an experience where you decided to take a break from social media.",
    "model": "Last semester, during our final exam week, I noticed I was constantly distracted by phone notifications, which made it impossible to focus. Therefore, I decided to do a digital detox and delete all social media apps for seven days. Initially, it felt quite strange and I had the urge to check my phone every few minutes. However, by the third day, I felt much calmer and had more quality time to study my textbooks and sleep. This temporary break greatly improved my concentration and exam scores.",
    "keywords": [
      "Take a break (休息一下/暫停)",
      "Final exam week (期末考週)",
      "Constantly distracted (不斷分心)",
      "Phone notifications (手機通知)",
      "Impossible to focus (無法專注)",
      "Digital detox (數位排毒/遠離電子產品)",
      "Delete apps (刪除應用程式)",
      "Initially (起初)",
      "Have the urge to (有...的衝動)",
      "Check my phone (看手機)",
      "Quality time (優質時間)",
      "Study textbooks (讀教科書)",
      "Temporary break (暫時的休息)",
      "Improve concentration (提升專專注力)",
      "Exam scores (考試分數)",
      "Relieve stress (減輕壓力)",
      "Stay offline (保持離線)",
      "Reality check (面對現實)",
      "Productive habits (高效率的習慣)",
      "Self-control (自我控制)"
    ]
  },
  {
    "number": 35,
    "category": "Success & Failure in Life",
    "title": "35. Major success you achieved in your school life",
    "prompt": "Describe a major success you achieved in your school life.",
    "model": "A major success in my school life was passing the intermediate level of the GEPT exam last year. Preparing for this English proficiency test was incredibly challenging because the reading and listening sections required a massive vocabulary. To achieve my goal, I created a strict study schedule, woke up early to memorize words, and practiced mock tests every weekend. When I received my passing certificate, I felt extremely proud. This success proved that my persistence pays off and gave me the confidence to prepare for studying in Singapore.",
    "keywords": [
      "Major success (重大成功)",
      "Intermediate level (中級階段)",
      "GEPT exam (全民英檢)",
      "English proficiency test (英文檢定)",
      "Incredibly challenging (極具挑戰性的)",
      "Reading & listening (閱讀與聽力部分)",
      "Massive vocabulary (龐大的字彙量)",
      "Achieve my goal (達成我的目標)",
      "Strict study schedule (讀書時間表)",
      "Memorize words (背單字)",
      "Mock tests (模擬考)",
      "Every weekend (每個週末)",
      "Passing certificate (合格證書)",
      "Feel extremely proud (感到無比自豪)",
      "Persistence pays off (堅持終有回報)",
      "Give me the confidence (給我信心)",
      "Academic milestone (學術里程碑)",
      "Overcome difficulty (克服困難)",
      "Language learning (語言學習)",
      "Future goals (未來目標)"
    ]
  },
  {
    "number": 36,
    "category": "Success & Failure in Life",
    "title": "36. Time you experienced failure and what you learned f...",
    "prompt": "Describe a time you experienced failure and what you learned from it.",
    "model": "Two years ago, I failed to make the school basketball team because my physical fitness and shooting skills weren't good enough. At that time, I felt completely devastated and wanted to give up the sport entirely. However, my father encouraged me to view this failure as a valuable learning opportunity. I started practicing my dribbling and running drills for an hour every day after school. Although I didn't join the team that year, this experience taught me resilience and showed me that failure is just a step toward improvement.",
    "keywords": [
      "Experience failure (經歷失敗)",
      "Make the team (入選球隊)",
      "Physical fitness (體能)",
      "Shooting skills (投籃技巧)",
      "Felt devastated (感到徹底崩潰/沮喪)",
      "Give up the sport (放棄這項運動)",
      "Valuable learning (寶貴的學習機會)",
      "Practice dribbling (練習運球)",
      "Running drills (跑步訓練)",
      "After school (放學後)",
      "Taught me resilience (教會我韌性)",
      "Step toward improvement (走向進步的一步)",
      "Deal with disappointment (處理失望)",
      "Constructive criticism (建設性的批評)",
      "Try my best (盡我最大的努力)",
      "Hard work (努力)",
      "Overcome setbacks (克服挫折)",
      "Keep moving forward (繼續前進)",
      "Personal growth (個人成長)",
      "Change my mindset (改變我的心態)"
    ]
  },
  {
    "number": 37,
    "category": "Success & Failure in Life",
    "title": "37. Explain what the word \"success\" means to you person...",
    "prompt": "Explain what the word \"success\" means to you personally.",
    "model": "To me, success does not simply mean getting high scores, earning a lot of money, or becoming famous. Instead, I believe true success is about making continuous personal progress and achieving the goals we set for ourselves. For example, overcoming my fear of speaking English and being able to communicate with foreigners is a great success for me. As long as we try our absolute best and learn from our mistakes along the way, we are already successful, regardless of the final outcome.",
    "keywords": [
      "Meaning of success (成功的定義)",
      "High scores (高分)",
      "Earn a lot of money (賺很多錢)",
      "Become famous (變有名)",
      "True success (真正的成功)",
      "Continuous personal progress (持續個人進步)",
      "Achieve goals (達成目標)",
      "Overcome fear (克服恐懼)",
      "Speak English (說英文)",
      "Communicate with foreigners (與外國人溝通)",
      "Try our absolute best (盡最大的努力)",
      "Learn from mistakes (從錯誤中學習)",
      "Along the way (在這過程中)",
      "Final outcome (最終結果)",
      "Self-improvement (自我提升)",
      "Define success (定義成功)",
      "Inner satisfaction (內心的滿足)",
      "Stay motivated (保持動力)",
      "Positive attitude (正向態度)",
      "Personal development (個人發展)"
    ]
  },
  {
    "number": 38,
    "category": "Success & Failure in Life",
    "title": "38. Failure or setback in a group project and how you h...",
    "prompt": "Describe a failure or setback in a group project and how you handled it.",
    "model": "Last semester, our science group project received a failing grade because we mismanaged our time and forgot to include essential data in our final report. We were all very disappointed and started blaming each other. Realizing that arguing wouldn't solve anything, I took the initiative to organize an emergency meeting. We apologized to our teacher, asked for a second chance, and worked together over the weekend to rewrite the report correctly. This setback taught me that clear communication and accountability are crucial for successful teamwork.",
    "keywords": [
      "Failure or setback (失敗或挫折)",
      "Group project (小組專案/報告)",
      "Failing grade (不及格的分數)",
      "Mismanage time (時間管理不當)",
      "Essential data (重要數據)",
      "Final report (最終報告)",
      "Disappointed (失望的)",
      "Blame each other (互相怪罪)",
      "Solve anything (解決任何事)",
      "Take the initiative (採取主動)",
      "Emergency meeting (緊急會議)",
      "Ask for a second chance (第二次機會)",
      "Worked together (一起工作)",
      "Weekend work (週末工作)",
      "Rewrite the report (重寫報告)",
      "Clear communication (清晰的溝通)",
      "Accountability (責任感/負責)",
      "Crucial for teamwork (對團隊合作至關重要)",
      "Handle pressure (處理壓力)",
      "Solve problems collectively (共同解決問題)"
    ]
  },
  {
    "number": 39,
    "category": "Methods of Learning & Overcoming Obstacles",
    "title": "39. Your favorite way to learn English outside of the c...",
    "prompt": "Describe your favorite way to learn English outside of the classroom.",
    "model": "My favorite way to learn English outside of the classroom is by watching popular Western YouTube channels and Netflix series with English subtitles. I prefer this method because it exposes me to authentic conversational English and natural accents, which are rarely found in traditional grammar textbooks. Whenever I encounter an unfamiliar vocabulary word or phrase, I pause the video and look it up on my phone. This engaging approach makes language learning incredibly fun, and it significantly improves my everyday listening and speaking skills.",
    "keywords": [
      "Learn English outside (課堂外學英文)",
      "YouTube channels (YouTube頻道)",
      "Netflix series (Netflix影集)",
      "English subtitles (英文字幕)",
      "Expose to (接觸...)",
      "Authentic conversation (生活口說英語)",
      "Natural accents (自然口音)",
      "Traditional textbooks (傳統教科書)",
      "Unfamiliar words (遇到不熟悉的單字)",
      "Pause the video (暫停影片)",
      "Look it up (查單字)",
      "Engaging approach (具吸引力的方法)",
      "Fun language learning (趣味語言學習)",
      "Significantly improve (顯著改善)",
      "Everyday listening (日常聽力技巧)",
      "Speaking skills (口說技巧)",
      "Practical learning (實用學習)",
      "Vocabulary retention (字彙記憶力)",
      "Entertainment (娛樂)",
      "Self-study method (自學方法)"
    ]
  },
  {
    "number": 40,
    "category": "Methods of Learning & Overcoming Obstacles",
    "title": "40. Difficult school subject and how you try to master it",
    "prompt": "Describe a difficult school subject and how you try to master it.",
    "model": "For me, Mathematics is the most difficult subject because it requires complex abstract thinking and memorizing countless formulas. I used to feel very anxious before every math test. To overcome this obstacle, I started changing my study strategy. Now, after every class, I regularly review the teacher's examples and practice solving at least ten different problems at night. If I get stuck, I immediately ask my classmates or teacher for clarification. This consistent effort has gradually improved my understanding and boosted my confidence.",
    "keywords": [
      "Difficult subject (困難的科目)",
      "Mathematics (數學)",
      "Complex abstract thinking (複雜抽象思考)",
      "Memorize formulas (記公式)",
      "Feel anxious (感到焦慮)",
      "Overcome this obstacle (克服這個障礙)",
      "Change study strategy (改變讀書策略)",
      "Regularly review (定期複習)",
      "Teacher's examples (老師的範例)",
      "Practice solving problems (練習解題)",
      "Get stuck (卡住/不會寫)",
      "Ask for clarification (尋求解答)",
      "Consistent effort (持續的努力)",
      "Gradually improve (逐漸進步)",
      "Boost confidence (提升信心)",
      "Academic challenges (學術挑戰)",
      "Analytical skills (分析能力)",
      "Ask questions (發問)",
      "Test preparation (考試準備)",
      "Better understanding (更好的理解)"
    ]
  },
  {
    "number": 41,
    "category": "Methods of Learning & Overcoming Obstacles",
    "title": "41. Obstacle you faced while preparing to study abroad...",
    "prompt": "Describe an obstacle you faced while preparing to study abroad and how you overcame it.",
    "model": "An obstacle I faced while preparing to study abroad in Singapore was my severe anxiety about passing the iTEP English speaking exam. At first, I would freeze and stutter whenever I had to answer prompts within the strict 45-second limit. To overcome this, I used a voice recording app on my smartphone to practice every single night. I timed my responses and listened to the recordings to correct my grammar and pacing errors. Eventually, this regular practice helped me speak fluently and reduced my exam anxiety.",
    "keywords": [
      "Obstacle faced (面對的障礙)",
      "Study abroad (去新加坡留學)",
      "Severe anxiety (嚴重的焦慮)",
      "Speaking exam (英文口說測驗)",
      "Freeze and stutter (僵住且結巴)",
      "Answer prompts (回答題目)",
      "Strict time limit (嚴格的時間限制)",
      "Voice recording app (語音錄音App)",
      "Every single night (每一晚)",
      "Time my responses (幫我的回答計時)",
      "Listen to recordings (聽錄音)",
      "Correct grammar (糾正文法)",
      "Pacing errors (節奏/語速錯誤)",
      "Speak fluently (流利地說)",
      "Reduce anxiety (減輕焦慮)",
      "Test preparation (考試準備)",
      "Gain confidence (獲得信心)",
      "Persistent practice (持續不斷的練習)",
      "Language barrier (語言隔閡)",
      "Goal-oriented (目標導向的)"
    ]
  },
  {
    "number": 42,
    "category": "Methods of Learning & Overcoming Obstacles",
    "title": "42. Talk about the importance of learning English in th...",
    "prompt": "Talk about the importance of learning English in the digital age.",
    "model": "In the digital age, I believe learning English is absolutely essential because it is the global language of technology and the internet. Most online resources, academic papers, and advanced software programs are created in English. If we only know Chinese, our access to information will be extremely limited. Furthermore, learning English allows us to communicate with people from diverse cultures worldwide and opens up global career opportunities. It is an indispensable tool that empowers us to become successful global citizens.",
    "keywords": [
      "Digital age (數位時代)",
      "Absolutely essential (絕對必要的)",
      "Global language (全球語言)",
      "Technology & internet (科技與網路)",
      "Online resources (網路資源)",
      "Academic papers (學術論文)",
      "Advanced software (先進軟體)",
      "Access to information (獲取資訊管道)",
      "Extremely limited (非常有限的)",
      "Communicate with people (與人溝通)",
      "Diverse cultures (多元文化)",
      "Career opportunities (全球職涯機會)",
      "Indispensable tool (不可或缺的工具)",
      "Empower someone to (賦予某人能力去...)",
      "Global citizens (世界公民)",
      "International communication (國際交流)",
      "Acquire knowledge (獲得知識)",
      "Broaden horizons (開闊視野)",
      "Modern world (現代世界)",
      "Stay competitive (保持競爭力)"
    ]
  },
  {
    "number": 43,
    "category": "Methods of Learning & Overcoming Obstacles",
    "title": "43. Study habit that you find most effective",
    "prompt": "Describe a study habit that you find most effective.",
    "model": "The study habit I find most effective is using the Pomodoro Technique to manage my time. This method involves focusing entirely on my schoolwork for twenty-five minutes, followed by a short five-minute break to stretch or drink water. I prefer this routine because it prevents me from feeling mentally exhausted during long study sessions. It also stops me from checking my phone constantly. Using this technique has significantly boosted my learning productivity and helped me prepare for my exams efficiently.",
    "keywords": [
      "Effective study habit (有效的讀書習慣)",
      "Pomodoro Technique (番茄鐘工作法)",
      "Manage time (管理時間)",
      "Focus entirely on (完全專注於...)",
      "Schoolwork (學校功課)",
      "Short break (短暫休息)",
      "Stretch (伸展)",
      "Drink water (喝水)",
      "Prevent from feeling exhausted (防止精疲力竭)",
      "Mentally exhausted (精神疲憊的)",
      "Long study sessions (長時間的讀書時段)",
      "Stop checking phone (阻止看手機)",
      "Significantly boosted (顯著提升)",
      "Learning productivity (學習生產力/效率)",
      "Prepare for exams (準備考試)",
      "Efficiently (有效率地)",
      "Concentration (專專注力)",
      "Stay organized (保持條理)",
      "Time management skill (時間管理技巧)",
      "Daily routine (日常慣例)"
    ]
  },
  {
    "number": 44,
    "category": "Hosting, Performance & Conflicts",
    "title": "44. Experience when you had to perform on stage or host...",
    "prompt": "Describe an experience when you had to perform on stage or host an event.",
    "model": "Last year, during our school's New Year celebration, I had the exciting experience of hosting the talent show in front of the entire school. Initially, standing backstage, my hands were shaking and I felt incredibly nervous about forgetting my script. However, once I walked out onto the stage and saw my classmates cheering for me, I took a deep breath and smiled. The event went smoothly, and the audience laughed at my jokes. It was a thrilling experience that significantly boosted my public speaking confidence.",
    "keywords": [
      "Perform on stage (在舞台上表演)",
      "Host an event (主持活動)",
      "New Year celebration (新年慶祝)",
      "Talent show (才藝表演)",
      "Entire school (全校)",
      "Standing backstage (站在後台)",
      "Hands were shaking (手在發抖)",
      "Incredibly nervous (無比緊張)",
      "Forget my script (忘記講稿)",
      "Walk out onto stage (走向舞台)",
      "Classmates cheering (同學歡呼)",
      "Take a deep breath (深吸一口氣)",
      "Go smoothly (順利進行)",
      "Audience laughed (觀眾笑了)",
      "Thrilling experience (刺激的經驗)",
      "Public speaking (公開演講自信)",
      "Master of ceremonies / MC (主持人)",
      "Overcome stage fright (克服舞台恐懼)",
      "Memorable moment (難忘時刻)",
      "Bright stage lights (明亮的舞台燈光)"
    ]
  },
  {
    "number": 45,
    "category": "Hosting, Performance & Conflicts",
    "title": "45. Time you had an interpersonal conflict with a frien...",
    "prompt": "Describe a time you had an interpersonal conflict with a friend and how you resolved it.",
    "model": "A few months ago, my close friend and I had a major interpersonal conflict because of a simple misunderstanding. She thought I was ignoring her messages on purpose, but the truth was that I was busy preparing for a difficult math test. She stopped talking to me at school, which made me feel very upset. To resolve the conflict, I approached her during recess, explained the situation honestly, and apologized for making her feel neglected. We gave each other a hug and promised to communicate better.",
    "keywords": [
      "Interpersonal conflict (人際衝突)",
      "Close friend (摯友)",
      "Simple misunderstanding (單純的誤會)",
      "Ignoring messages (不讀不回訊息)",
      "On purpose (故意地)",
      "Busy preparing for tests (忙於準備考試)",
      "Stop talking to me (不跟我說話)",
      "Feel very upset (感到難過/沮喪)",
      "Resolve conflict (解決衝突)",
      "Approach someone (走近某人)",
      "During recess (下課時間)",
      "Explain honestly (誠實解釋情況)",
      "Apologize (道歉)",
      "Feel neglected (感到被忽視)",
      "Give a hug (擁抱)",
      "Communicate better (更好地溝通)",
      "Rebuild trust (重建信任)",
      "True friendship (真正的友誼)",
      "Express feelings openly (公開表達感受)",
      "Clear the air (消除誤會)"
    ]
  },
  {
    "number": 46,
    "category": "Hosting, Performance & Conflicts",
    "title": "46. Discuss the generation gap between you and your par...",
    "prompt": "Discuss the generation gap between you and your parents.",
    "model": "In my family, the generation gap between me and my parents is most obvious when it comes to technology and future career choices. My parents believe that I spend too much time on my smartphone and prefer traditional careers like being a doctor or a lawyer. On the other hand, I view my phone as an essential tool for learning and entertainment, and I dream of studying digital media in Singapore. To bridge this gap, I try to patiently explain my ideas and show them how modern technology works.",
    "keywords": [
      "Generation gap (代溝)",
      "Obvious (明顯的)",
      "When it comes to (當談到...)",
      "Career choices (職涯選擇)",
      "Spend too much time (花太多時間)",
      "Traditional careers (傳統職涯)",
      "On the other hand (另一方面)",
      "Essential tool (不可或缺的工具)",
      "Digital media (數位媒體)",
      "Bridge the gap (縮短/搭起橋梁)",
      "Patiently explain (耐心地解釋)",
      "Different perspectives (不同的觀點)",
      "Mutual respect (互相尊重)",
      "Parent-child relationship (親子關係)",
      "Open communication (開放式溝通)",
      "Cultural shift (文化轉變)",
      "Lifestyle differences (生活方式差異)",
      "Express my thoughts (表達我的想法)",
      "Family discussion (家庭討論)",
      "Listen to advice (聽取建議)"
    ]
  },
  {
    "number": 47,
    "category": "Hosting, Performance & Conflicts",
    "title": "47. Experience working in a team where people had diffe...",
    "prompt": "Describe an experience working in a team where people had different opinions.",
    "model": "During an English group project last month, our team members had conflicting opinions about how to design our posters. Some wanted to use hand-drawn art, while others preferred digital graphics. The disagreement delayed our progress. As the group leader, I organized a short meeting where everyone had one minute to state their preference. We finally agreed to a creative compromise: using digital layouts but incorporating hand-drawn text elements. By listening to everyone, we finished on time and got an A.",
    "keywords": [
      "Work in a team (團隊工作)",
      "Conflicting opinions (衝突的意見)",
      "Design posters (設計海報)",
      "Hand-drawn art (手繪藝術)",
      "Digital graphics (數位圖形/設計)",
      "Delay progress (延誤進度)",
      "Group leader (小組長)",
      "Organize a meeting (組織會議)",
      "State their preference (陳述偏好)",
      "Creative compromise (有創意的折衷)",
      "Incorporate elements (融入元素)",
      "Finish on time (準時完成)",
      "Different perspectives (不同觀點)",
      "Brainstorming session (腦力激盪)",
      "Team collaboration (團隊合作)",
      "Active listening (積極傾聽)",
      "Achieve a goal (達成目標)",
      "Mutual agreement (共同協議)",
      "Problem-solving (解決問題)",
      "Project deadline (專案截止日期)"
    ]
  },
  {
    "number": 48,
    "category": "School Events & Field Trips",
    "title": "48. Your school's annual swimming carnival or sports day",
    "prompt": "Describe your school's annual swimming carnival or sports day.",
    "model": "Every autumn, our school hosts an exciting annual swimming carnival at the local sports center. It is one of the most energetic days of the school year. All the classes wear different colored T-shirts and sit in the stands to cheer loudly for their swimmers. Last year, I competed in the freestyle relay race. Although our team didn't win first place, the thrilling experience of racing through the water while hearing my classmates shout my name was unforgettable. It really boosted our class unity.",
    "keywords": [
      "Annual swimming carnival (水上運動會)",
      "Sports day (運動會)",
      "Energetic days (活力充沛的日子)",
      "Wear colored T-shirts (穿彩色T恤)",
      "Sit in the stands (坐在看台上)",
      "Cheer loudly (大聲歡呼)",
      "Compete in a race (參加比賽)",
      "Freestyle relay (自由式接力)",
      "Thrilling experience (刺激的經驗)",
      "Class unity (班級凝聚力)",
      "Competitors (選手)",
      "Team spirit (團隊精神)",
      "Swimming pool (游泳池)",
      "Shout my name (喊我的名字)",
      "Unforgettable memories (難忘的回憶)",
      "Fun activities (趣味活動)",
      "School event (學校活動)",
      "Win a medal (贏得獎牌)",
      "Support each other (互相支持)",
      "Atmosphere was electric (氣氛熱烈)"
    ]
  },
  {
    "number": 49,
    "category": "School Events & Field Trips",
    "title": "49. Christmas celebration or winter event at your school",
    "prompt": "Describe a Christmas celebration or winter event at your school.",
    "model": "My school hosts a wonderful Christmas celebration every December. The entire campus is beautifully decorated with colorful lights, a massive Christmas tree, and handmade ornaments. The highlight of the day is the class gift exchange game and the singing competition, where we perform classic carols in English. Our teachers dress up as Santa Claus and hand out chocolates to everyone. It creates a warm, festive atmosphere that helps us relax and feel joyful before the stressful final exams approach.",
    "keywords": [
      "Christmas celebration (聖誕慶祝)",
      "Beautifully decorated (裝飾精美的)",
      "Massive Christmas tree (巨大的聖誕樹)",
      "Handmade ornaments (手工裝飾品)",
      "Highlight of the day (最精彩的部分)",
      "Gift exchange game (交換禮物遊戲)",
      "Singing competition (歌唱比賽)",
      "Classic carols (經典頌歌)",
      "Dress up as Santa (打扮成聖誕老人)",
      "Hand out chocolates (發巧克力)",
      "Festive atmosphere (節日氣氛)",
      "Feel joyful (感到快樂)",
      "Stressful final exams (期末考)",
      "Winter event (冬季活動)",
      "Holiday season (節日季)",
      "Spread happiness (傳遞快樂)",
      "School tradition (學校傳統)",
      "Sing together (一起唱歌)",
      "Warm memories (溫暖的回憶)",
      "Celebrate together (一起慶祝)"
    ]
  },
  {
    "number": 50,
    "category": "School Events & Field Trips",
    "title": "50. Memorable class field trip you went on",
    "prompt": "Describe a memorable class field trip you went on.",
    "model": "Last semester, our class went on an educational field trip to the National Palace Museum in Taipei. We traveled together by school bus, and everyone was extremely excited. A professional tour guide showed us famous ancient Chinese artifacts, like the famous Jadeite Cabbage. Seeing these historical treasures in person was much more fascinating than just reading about them in our history textbooks. This field trip broadened my horizons and allowed me to bond with my classmates outside of our classroom.",
    "keywords": [
      "Class field trip (班級校外教學)",
      "Educational trip (教育之旅)",
      "National Palace Museum (故宮博物院)",
      "Travel by bus (搭巴士旅行)",
      "Professional tour guide (專業導遊)",
      "Ancient Chinese artifacts (中國文物)",
      "Jadeite Cabbage (翠玉白菜)",
      "Historical treasures (歷史寶物)",
      "In person (親自/親眼)",
      "Fascinating (迷人的)",
      "History textbooks (歷史教科書)",
      "Broaden horizons (開闊視野)",
      "Bond with classmates (與同學建立感情)",
      "Outside the classroom (在教室外)",
      "Cultural heritage (文化遺產)",
      "Group activity (小組活動)",
      "Learn outside school (校外學習)",
      "Take notes (做筆記)",
      "Memorable experience (難忘的經驗)",
      "Informative (長見聞的)"
    ]
  },
  {
    "number": 51,
    "category": "School Events & Field Trips",
    "title": "51. Talk about a school club activity you participate in",
    "prompt": "Talk about a school club activity you participate in.",
    "model": "I am an active member of our school's English Drama Club. We meet every Wednesday afternoon in the school theater to practice acting, scriptwriting, and pronunciation. Participating in this club has been a fantastic experience because it allows me to practice my English speaking skills in a highly creative and playful environment. Right now, we are rehearsing a short play for the upcoming school anniversary. It helps me express myself confidently and work closely with students from different classes.",
    "keywords": [
      "Active member (活躍的成員)",
      "English Drama Club (英文話劇社)",
      "School theater (學校劇場)",
      "Practice acting (練習表演)",
      "Scriptwriting (劇本寫作)",
      "Pronunciation (發音)",
      "Fantastic experience (奇妙的經驗)",
      "Creative environment (有創意的環境)",
      "Rehearsing a play (排練戲劇)",
      "School anniversary (校慶)",
      "Express confidently (自信地表達自己)",
      "Different classes (不同的班級)",
      "Teamwork (團隊合作)",
      "Build social skills (建立社交技巧)",
      "Extracurricular activity (課外活動)",
      "Weekly meeting (每週會議/社課)",
      "Performance skills (表演技巧)",
      "Overcome shyness (克服害羞)",
      "Fun learning (有趣的學習)",
      "Creative outlet (創意的宣洩管道)"
    ]
  },
  {
    "number": 52,
    "category": "School Events & Field Trips",
    "title": "52. The rules at your school and your opinion about them",
    "prompt": "Describe the rules at your school and your opinion about them.",
    "model": "Our school has several strict rules, such as wearing our uniform properly every day and turning off our smartphones during class hours. In my opinion, most of these regulations are reasonable because they help maintain a structured and polite learning environment. For instance, banning phones prevents us from getting distracted during lectures. However, I think the rule against having different hairstyles is a bit outdated. Teenagers should be allowed to express their individuality as long as they focus on their studies.",
    "keywords": [
      "Strict rules (嚴格的校規)",
      "Wear uniform properly (正確穿制服)",
      "Turn off smartphones (關手機)",
      "Class hours (上課時間)",
      "School regulations (學校規定)",
      "Structured environment (有條理的環境)",
      "Polite learning environment (禮貌的環境)",
      "Ban phones (禁手機)",
      "Prevent distraction (防止分心)",
      "Outdated rule (過時的規定)",
      "Express individuality (表達個人特質)",
      "Focus on studies (專注於學業)",
      "Maintain discipline (維持紀律)",
      "Follow guidelines (遵守指導方針)",
      "Academic focus (學術專注)",
      "Reasonable rules (合理的規則)",
      "Mutual respect (互相尊重)",
      "Strict enforcement (嚴格執行)",
      "Personal freedom (個人自由)",
      "Student behavior (學生行為)"
    ]
  },
  {
    "number": 53,
    "category": "Travel & Family Holidays",
    "title": "53. Special holiday you took with your parents",
    "prompt": "Describe a special holiday you took with your parents.",
    "model": "Two years ago, during the summer vacation, my parents and I took an unforgettable two-week trip to Japan. We visited Tokyo and Kyoto, exploring beautiful ancient temples and modern shopping districts. What made this holiday special was that we slowed down our pace and spent quality time chatting during long train rides. We enjoyed delicious authentic sushi and ramen together every day. This trip brought our family closer, and it provided a wonderful escape from our busy daily routines in Taiwan.",
    "keywords": [
      "Special holiday (非凡的假期)",
      "Summer vacation (暑假)",
      "Unforgettable trip (難忘的旅行)",
      "Ancient temples (古老寺廟)",
      "Modern shopping districts (現代購物區)",
      "Slow down our pace (放慢我們的步伐)",
      "Spent quality time (度過優質時間)",
      "Long train rides (長途火車之旅)",
      "Authentic sushi (道地壽司)",
      "Brought family closer (讓家庭更緊密)",
      "Wonderful escape (美好的逃離/放鬆)",
      "Busy daily routines (忙碌的日常慣例)",
      "Travel together (一起旅行)",
      "Family bond (家庭情感)",
      "Explore new cultures (探索新文化)",
      "Beautiful scenery (美麗風景)",
      "Local cuisine (在地美食)",
      "Precious memories (珍貴的回憶)",
      "Sightseeing (觀光)",
      "Relieve stress (減輕壓力)"
    ]
  },
  {
    "number": 54,
    "category": "Travel & Family Holidays",
    "title": "54. Road trip experience in a private SUV through Canada",
    "prompt": "Describe a road trip experience in a private SUV through Canada.",
    "model": "Last summer, my family went on an incredible backpacking road trip through western Canada. My father rented a spacious, private SUV, and we drove through the majestic Rocky Mountains. Being in our own vehicle gave us the freedom to stop whenever we saw breathtaking scenery, like the turquoise waters of Lake Louise. We stayed in cozy local lodges and hiked along natural trails every day. Driving through Canada's vast wilderness was a refreshing experience that taught me to deeply appreciate the wonders of nature.",
    "keywords": [
      "Road trip experience (公路旅行經驗)",
      "Backpacking trip (自助背包客旅行)",
      "Rent a spacious SUV (租一輛寬敞的SUV)",
      "Private vehicle (私人車輛)",
      "Majestic mountains (雄偉的山脈)",
      "Rocky Mountains (落基山脈)",
      "Breathtaking scenery (美到令人窒息的風景)",
      "Turquoise waters (松石綠的海水/湖水)",
      "Cozy local lodges (溫馨的當地旅館)",
      "Hike along trails (沿著步道健行)",
      "Vast wilderness (廣闊的荒野)",
      "Refreshing experience (令人耳目一新的經驗)",
      "Appreciate nature (欣賞大自然)",
      "Freedom to travel (旅行的自由)",
      "Driving vacation (自駕渡假)",
      "Spectacular views (壯觀的景色)",
      "Family adventure (家族冒險)",
      "Wildlife spotting (觀察野生動物)",
      "Unspoiled nature (未受破壞的大自然)",
      "Cross-country travel (跨國/跨區旅行)"
    ]
  },
  {
    "number": 55,
    "category": "Travel & Family Holidays",
    "title": "55. Discuss the advantages of traveling by a private ca...",
    "prompt": "Discuss the advantages of traveling by a private car versus public transportation.",
    "model": "In my opinion, traveling by a private car or SUV offers much more flexibility and comfort compared to public transportation. When you drive your own vehicle, you can choose your own schedule, stop anywhere to take photos, and carry heavy luggage without stress. However, public transport like trains and buses is more environmentally friendly and cheaper. For long-distance family road trips in nature, a private car is definitely better, but for exploring crowded cities, public transit is more convenient and avoids traffic jams.",
    "keywords": [
      "Advantages of traveling (旅行的優點)",
      "Private car (私家車)",
      "SUV (休旅車)",
      "Flexibility and comfort (靈活性與舒適度)",
      "Public transportation (大眾運輸)",
      "Choose own schedule (選擇自己的行程)",
      "Take photos (拍照)",
      "Carry heavy luggage (搬重行李)",
      "Environmentally friendly (環保的)",
      "Long-distance road trips (長途公路旅行)",
      "Crowded cities (擁擠的城市)",
      "Public transit (大眾運輸系統)",
      "Avoid traffic jams (避免交通堵塞)",
      "Travel option (旅遊選擇)",
      "Cost-effective (划算的)",
      "Freedom of movement (移動自由)",
      "Fuel efficiency (燃油效率)",
      "Commute (通勤)",
      "Convenient (方便的)",
      "Travel comparison (旅遊比較)"
    ]
  },
  {
    "number": 56,
    "category": "Travel & Family Holidays",
    "title": "56. Your dream travel destination and what you want to...",
    "prompt": "Describe your dream travel destination and what you want to do there.",
    "model": "My dream travel destination is the United Kingdom, specifically London. I am eager to visit this historic city because I want to see famous landmarks like Big Ben, the London Eye, and the British Museum in person. Furthermore, as an English learner, I look forward to practicing my speaking skills with native speakers and experiencing British culture firsthand. I also want to watch a famous musical theater performance in the West End. It would be an enriching journey that combines education with entertainment.",
    "keywords": [
      "Dream travel destination (夢想目的地)",
      "United Kingdom / London (英國/倫敦)",
      "Historic city (歷史悠久的城市)",
      "Famous landmarks (著名地標)",
      "Big Ben (大笨鐘)",
      "British Museum (大英博物館)",
      "In person (親自)",
      "English learner (英文學習者)",
      "Practice speaking (練習口說技巧)",
      "Native speakers (母語人士)",
      "Experience firsthand (親身體驗文化)",
      "Musical theater (音樂劇劇場)",
      "Enriching journey (充實的旅程)",
      "Combine education (寓教於樂)",
      "Sightseeing (觀光)",
      "Broaden my mind (開闊心胸)",
      "Cultural exploration (文化探索)",
      "Travel itinerary (旅行行程)",
      "Historic architecture (歷史建築)",
      "High on bucket list (在願望清單前列)"
    ]
  },
  {
    "number": 57,
    "category": "Travel & Family Holidays",
    "title": "57. Unexpected problem you faced during a trip and how...",
    "prompt": "Describe an unexpected problem you faced during a trip and how you solved it.",
    "model": "Last year, during a family trip to Hualien, we faced a stressful problem when my father accidentally lost our hotel room key card and wallet at a crowded night market. We were deeply worried because all our cash and credit cards were inside. To solve this crisis, I immediately used my smartphone to look up the bank's hotline and help my parents freeze the cards. Then, we contacted the night market service center. Luckily, an honest vendor found it and handed it in. This taught me to stay calm.",
    "keywords": [
      "Unexpected problem (意料之外的問題)",
      "Family trip (家族旅行)",
      "Stressful situation (充滿壓力的情況)",
      "Accidentally lost (不小心遺失)",
      "Crowded night market (擁擠的夜市)",
      "Deeply worried (深深擔憂)",
      "Solve this crisis (解決這個危機)",
      "Bank hotline (銀行客服專線)",
      "Freeze the cards (凍結信用卡)",
      "Contact service center (聯絡服務中心)",
      "Honest vendor (誠實的攤商)",
      "Hand it in (交出來/歸還)",
      "Stay calm (保持冷靜)",
      "Travel safety (旅遊安全)",
      "Emergency situation (緊急狀況)",
      "Valuable lesson (寶貴的一課)",
      "Smart technology (智慧科技)",
      "Financial security (財務安全)",
      "Keep an eye on possessions (看管財物)",
      "Relief (鬆了一口氣)"
    ]
  },
  {
    "number": 58,
    "category": "Travel & Family Holidays",
    "title": "58. Talk about a place in Taiwan you like to visit duri...",
    "prompt": "Talk about a place in Taiwan you like to visit during long weekends.",
    "model": "During long weekends, I love visiting Jiaoxi in Yilan. Located just an hour away from Taipei via the highway, it is the perfect destination for a short family getaway. Jiaoxi is world-famous for its natural hot springs. My family usually stays at a local hot spring hotel to soak in the mineral water, which instantly relieves our physical tiredness and academic stress. We also enjoy walking around the peaceful town and eating local snacks like green onion pancakes. It is a deeply relaxing environment.",
    "keywords": [
      "Long weekends (連續假期)",
      "Short family getaway (短暫的家庭度假)",
      "Hot spring hotel (溫泉飯店)",
      "Relieve academic stress (紓解課業壓力)",
      "Local snacks (在地小吃)",
      "Green onion pancakes (蔥油餅)",
      "Relaxing environment (讓人放鬆的環境)",
      "Mineral water (礦物質泉水)",
      "Physical tiredness (身體疲勞)",
      "Peaceful town (寧靜的小鎮)",
      "Via the highway (走高速公路)",
      "Popular destination (熱門目的地)",
      "Soak in hot springs (泡溫泉)",
      "Refreshing trip (令人精神振奮的旅行)",
      "Local tourism (在地觀光)",
      "Perfect escape (完美逃離/放鬆)",
      "Close to nature (接近大自然)",
      "Family time (家庭時光)",
      "Leisure activity (休閒活動)",
      "Scenic views (風景優美的景色)"
    ]
  },
  {
    "number": 59,
    "category": "Travel & Family Holidays",
    "title": "59. The most beautiful natural scenery you have ever se...",
    "prompt": "Describe the most beautiful natural scenery you have ever seen while traveling.",
    "model": "The most beautiful natural scenery I have ever seen was the sunrise over Alishan during our winter trip last year. We woke up at four in the morning and took a small forest train to the viewing deck. When the sun slowly rose above the horizon, it illuminated a massive, breathtaking ocean of clouds below the mountain peaks. The sky turned vibrant shades of orange, pink, and gold. Looking at that spectacular view made me forget the freezing temperature completely. It was a magical moment of pure natural beauty.",
    "keywords": [
      "Beautiful scenery (美麗的自然風景)",
      "Sunrise over Alishan (阿里山日出)",
      "Winter trip (冬季旅行)",
      "Forest train (森林小火車)",
      "Viewing deck (觀景台)",
      "Rose above horizon (升起於地平線)",
      "Illuminated (照亮)",
      "Ocean of clouds (美到令人窒息的雲海)",
      "Mountain peaks (山峰)",
      "Vibrant shades (鮮豔的色彩變化)",
      "Spectacular view (壯觀的景色)",
      "Freezing temperature (寒冷的溫度)",
      "Magical moment (魔幻時刻)",
      "Pure natural beauty (純粹自然之美)",
      "Wonder of nature (大自然的奇蹟)",
      "Early morning (清晨)",
      "Take a trip (旅行)",
      "Unforgettable sight (難忘的景象)",
      "Landscape photography (風景攝影)",
      "Majestic scenery (雄偉的風景)"
    ]
  },
  {
    "number": 60,
    "category": "Travel & Family Holidays",
    "title": "60. Explain why you think backpacking is a good way for...",
    "prompt": "Explain why you think backpacking is a good way for young people to travel.",
    "model": "In my opinion, backpacking is an excellent way for young people to travel because it fosters independence, budget-awareness, and problem-solving skills. Unlike luxury tours, backpackers must plan their own itineraries, navigate public transport, and manage a strict budget. This challenging process forces us to interact with locals and adapt to unexpected changes. Furthermore, staying in youth hostels allows backpackers to meet foreign travelers from diverse backgrounds. It is an active form of learning that builds resilience and broadens our global horizons significantly.",
    "keywords": [
      "Backpacking (自助背包客旅行)",
      "Foster independence (培養獨立性)",
      "Budget-awareness (預算意識)",
      "Problem-solving skills (解決問題能力)",
      "Plan itineraries (規劃行程)",
      "Navigate transport (搭乘大眾運輸)",
      "Manage strict budget (管理嚴格的預算)",
      "Challenging process (具挑戰性的過程)",
      "Interact with locals (與當地人互動)",
      "Adapt to changes (適應改變)",
      "Youth hostels (青年旅館)",
      "Meet foreign travelers (結識外國旅客)",
      "Diverse backgrounds (多元背景)",
      "Active learning (主動的學習形式)",
      "Build resilience (建立韌性/適應力)",
      "Broaden horizons (開闊全球視野)",
      "Low-cost travel (低成本旅遊)",
      "Independent travel (獨立旅行)",
      "Life experience (人生經驗)",
      "Self-reliance (自力更生)"
    ]
  }
];
